### ISSUE TITLE
Correct usage of -network flag

### ISSUE THREAD

**Issue by faddat** [ka2n/masminer#1]
Hi!

I think I love your work, but I think I'm using it wrong.  It seems like you have masminer set to autodetect miners, which is awesome.  But right now, all I can get it to do is detect a single miner, like this:

```
./masminer -network 192.168.6.101
```

When I give it a range, like 

```
./masminer -network 192.168.6.101 192.168.6.254
```

It goes back to not working.  If I'm wrong, and this hasn't been implemented yet, I'd love to help.  I haven't read through the libraries yet, just the "cmd".  

Thanks,
-Jake

**Comment by faddat** [comment]
I've basically solved this issue, but want to document it here for anyone else looking:  The correct way is to use a CIDR eg:

192.168.7.0/24

That gets e'r good.  

My Halong miners crash masminer, and I don't fully understand what the program is doing (I guess not all the output from the miners is written to the terminal output of the application?)  but I am certainly having a much better time. 

I'm running this in my mine, on a Raspberry Pi.  

Thank you, @ka2n , for sharing the fruits of your work!  Once I understand it a bit better, I'm interested in contributing.

**Comment by ka2n** [comment]
Hi @faddat !
Thank you for your interest in my project, and create 1st issue!

> It goes back to not working. If I'm wrong, and this hasn't been implemented yet, I'd love to help. I haven't read through the libraries yet, just the "cmd".

It may have you to misunderstand, `cmd/masminer` is just example of usage for this library.
In this case, you already know ASIC's IP address then you can use `asic.Client` directly.

And about the crashes, Haolong miners aren't supported yet. I have only Baikal, Antminer now. (I have a plan to support INNOSILICON in nearly future)
This project aim to create a single interface to ASICs from various manufactures. So I'm always your contribution welcome!

**Comment by ka2n** [comment]
Contribution welcome!
